### ISSUE TITLE
Couldn't load any collection file (Traktor 2.10.3)

### ISSUE THREAD

**Issue by MrKinsky** [andersfischernielsen/Traktor-Transition-Finder#32]
Hey,

i get all the time this Error Message, when i try to upload my collection file into the app.
Can you tell me how i can fix the problem?

Thank
Cheers
Martin

ERROR MESSAGE:

Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at parseKey (/Users/Kinsky/Downloads/TraktorTransitionFinder 2.app/Contents/Resources/app/graph.js:28:24)
    at parseToSong (/Users/Kinsky/Downloads/TraktorTransitionFinder 2.app/Contents/Resources/app/graph.js:76:66)
    at Array.map (native)
    at Function.parseCollection (/Users/Kinsky/Downloads/TraktorTransitionFinder 2.app/Contents/Resources/app/graph.js:79:32)
    at buildGraph (/Users/Kinsky/Downloads/TraktorTransitionFinder 2.app/Contents/Resources/app/main.js:58:41)
    at EventEmitter.ipc.on (/Users/Kinsky/Downloads/TraktorTransitionFinder 2.app/Contents/Resources/app/main.js:37:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Users/Kinsky/Downloads/TraktorTransitionFinder 2.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)

**Comment by andersfischernielsen** [comment]
See #23.

**Comment by svandragt** [comment]
I've sent you an email with my collection.nml from Traktor 2.0.11 where this still happens.

**Comment by andersfischernielsen** [comment]
Could you try the new 1.3.5 release found at https://github.com/andersfischernielsen/Traktor-Transition-Finder/releases?
