### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by NyarlaCat** [andersfischernielsen/Traktor-Transition-Finder#33]
I'm using Tracktor version 2.11.0 23 and Mac OS version 10.12.5 When I try to open my collection.nml I get this error message, what can I do to fix this?

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at parseKey (/Applications/TraktorTransitionFinder.app/Contents/Resources/app/graph.js:28:24)
    at parseToSong (/Applications/TraktorTransitionFinder.app/Contents/Resources/app/graph.js:76:66)
    at Array.map (native)
    at Function.parseCollection (/Applications/TraktorTransitionFinder.app/Contents/Resources/app/graph.js:79:32)
    at buildGraph (/Applications/TraktorTransitionFinder.app/Contents/Resources/app/main.js:58:41)
    at EventEmitter.ipc.on (/Applications/TraktorTransitionFinder.app/Contents/Resources/app/main.js:37:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Applications/TraktorTransitionFinder.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)

**Comment by zfogg** [comment]
+1

**Comment by andersfischernielsen** [comment]
Could you try the new 1.3.5 release found at https://github.com/andersfischernielsen/Traktor-Transition-Finder/releases?
